# Use postgres/postgres as user/password credentials
version: '3.1'

services:

  db:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  db2:
    image: postgres:15.4
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"