name: Deploy
on:
  push:
    branches:
      - master

permissions:
  packages: write

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Build
        run: docker build -t ghcr.io/proyectogshort/echo-core:latest .

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Push to GHCR
        run: docker push ghcr.io/proyectogshort/echo-core:latest

      - name: Delete old images
        uses: bots-house/ghcr-delete-image-action@v1.1.0
        with:
          owner: proyectogshort
          name: echo-core
          token: ${{ secrets.GITHUB_TOKEN }}
          untagged-keep-latest: 1

      - name: Kubernetes Set Context
        uses: Azure/k8s-set-context@v4.0.1
        with:
         kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Deploy to K8S
        run: kubectl rollout restart deploy/echo-backend
